#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-prabclus
Version  : 2.3.4
Release  : 55
URL      : https://cran.r-project.org/src/contrib/prabclus_2.3-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/prabclus_2.3-4.tar.gz
Summary  : Functions for Clustering and Testing of Presence-Absence,
Group    : Development/Tools
License  : GPL-2.0
Requires: R-mclust
BuildRequires : R-mclust
BuildRequires : R-spdep
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
spatial neighborhood information. Some distance measures, 
  Clustering of presence-absence, abundance and multilocus genetic data 
  for species delimitation, nearest neighbor 
  based noise detection. Genetic distances between communities.
  Tests whether various distance-based regressions
  are equal. Try package?prabclus for on overview.

%prep
%setup -q -n prabclus
pushd ..
cp -a prabclus buildavx2
popd
pushd ..
cp -a prabclus buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727186613

%install
export SOURCE_DATE_EPOCH=1727186613
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/prabclus/DESCRIPTION
/usr/lib64/R/library/prabclus/INDEX
/usr/lib64/R/library/prabclus/Meta/Rd.rds
/usr/lib64/R/library/prabclus/Meta/data.rds
/usr/lib64/R/library/prabclus/Meta/features.rds
/usr/lib64/R/library/prabclus/Meta/hsearch.rds
/usr/lib64/R/library/prabclus/Meta/links.rds
/usr/lib64/R/library/prabclus/Meta/nsInfo.rds
/usr/lib64/R/library/prabclus/Meta/package.rds
/usr/lib64/R/library/prabclus/NAMESPACE
/usr/lib64/R/library/prabclus/R/prabclus
/usr/lib64/R/library/prabclus/R/prabclus.rdb
/usr/lib64/R/library/prabclus/R/prabclus.rdx
/usr/lib64/R/library/prabclus/data/kykladspecreg.rda
/usr/lib64/R/library/prabclus/data/kykladspecreg.txt.gz
/usr/lib64/R/library/prabclus/data/nb.rda
/usr/lib64/R/library/prabclus/data/siskiyou.rda
/usr/lib64/R/library/prabclus/data/tetragonula.rda
/usr/lib64/R/library/prabclus/data/veronica.rda
/usr/lib64/R/library/prabclus/data/waterdist.rda
/usr/lib64/R/library/prabclus/data/waterdist.txt.gz
/usr/lib64/R/library/prabclus/extdata/00Index.old
/usr/lib64/R/library/prabclus/extdata/Franck04koord.txt
/usr/lib64/R/library/prabclus/extdata/Heterotrigona_indoFO.txt
/usr/lib64/R/library/prabclus/extdata/LeiMik1.txt
/usr/lib64/R/library/prabclus/extdata/LeiMik1G.txt
/usr/lib64/R/library/prabclus/extdata/LeiMik1NB.txt
/usr/lib64/R/library/prabclus/extdata/MartinezKoord.txt
/usr/lib64/R/library/prabclus/extdata/MartinezOrtega04AFLP.txt
/usr/lib64/R/library/prabclus/extdata/nb.R
/usr/lib64/R/library/prabclus/extdata/nb.txt
/usr/lib64/R/library/prabclus/extdata/siskiyou.R
/usr/lib64/R/library/prabclus/extdata/tetragonula.R
/usr/lib64/R/library/prabclus/extdata/veronica.R
/usr/lib64/R/library/prabclus/help/AnIndex
/usr/lib64/R/library/prabclus/help/aliases.rds
/usr/lib64/R/library/prabclus/help/paths.rds
/usr/lib64/R/library/prabclus/help/prabclus.rdb
/usr/lib64/R/library/prabclus/help/prabclus.rdx
/usr/lib64/R/library/prabclus/html/00Index.html
/usr/lib64/R/library/prabclus/html/R.css
/usr/lib64/R/library/prabclus/tests/Examples/prabclus-Ex.Rout.save
/usr/lib64/R/library/prabclus/tests/donttestexamples.R
/usr/lib64/R/library/prabclus/tests/prabclustests.R
/usr/lib64/R/library/prabclus/tests/prabclustests.Rout.save
